### ISSUE TITLE
Caching the configuration cause bugs

### ISSUE THREAD

**Issue by a-bashtannik** [uptime-development/laravel-socialite-criipto#1]
You have to refuse of using Cache for storing configuration or refactor the library, which I believe makes no sense. 

https://github.com/uptime-development/laravel-socialite-criipto/blob/main/src/SocialiteCriiptoProvider.php#L120 
and
https://github.com/uptime-development/laravel-socialite-criipto/blob/main/src/SocialiteCriiptoProvider.php#L137 

Criipto rotates the keys regularly and you will get problems with KID values trying to decode the response using cached values. 

> "kid" invalid, unable to lookup correct key

Support comment: 

> Each time you receive a JWT with a kid value you haven't seen before, you should fetch new metadata (once).
If the kid is present in the new metadata, you should update your cache and validate the token.
If not, you should reject the JWT.

**Comment by a-bashtannik** [comment]
And forgot to say, the default cache TTL for FileStorage (at least) is infinite if you have `$ttl === null` what is default package behavior.

**Comment by a-bashtannik** [comment]
Do you guys accept PRs?
cc @nickknissen @emilklindt @andersmandersen

**Comment by andersmandersen** [comment]
@a-bashtannik Yes, of course we do! Haven't had the time to look into my self yet :)
